# Generated by Django 4.1.7 on 2023-04-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(max_length=100)),
                ('dst_ip', models.CharField(max_length=100)),
                ('src_port', models.CharField(max_length=100)),
                ('dst_port', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.iotdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(max_length=100)),
                ('dst_ip', models.CharField(max_length=100)),
                ('src_port', models.CharField(max_length=100)),
                ('dst_port', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.iotdevice')),
            ],
        ),
    ]
